### ISSUE TITLE
getClientIPAddress fails on remix 1.7.2

### ISSUE THREAD

**Issue by cldellow** [sergiodxa/remix-utils#101]
### Describe the bug

When I use remix-utils with remix-run 1.7.2, getClientIPAddress starts to fail:

```
TypeError: headers.get is not a function
    at /home/cldellow/src/webapp/node_modules/remix-utils/build/server/get-client-id-address.js:32:29
    at Array.flatMap (<anonymous>)
    at getClientIPAddress (/home/cldellow/src/webapp/node_modules/remix-utils/build/server/get-client-id-address.js:31:10)
...
```

It seems like in https://github.com/sergiodxa/remix-utils/blob/3533f70dfd6b94638e26ba727917de5b22e6d716/src/server/get-headers.ts#L7, the `requestOrHeaders` object is still a `Request`, but the instanceof check is no longer returning true, which causes remix-utils to return the `Request` object. Calling `.get(...)` on that then fails.

**Comment by cldellow** [comment]
This is maybe related to remix's changes to use @remix-run/web-fetch? `requestOrHeaders` seems to be a `NodeRequest`, which I think comes from that package.

For now I'm using patch-package to change the test from an instanceof to a check of `typeof requestOrHeaders?.headers?.get === 'function'`

**Comment by sergiodxa** [comment]
@cldellow could you confirm this still happens with v5.0.1?

**Comment by sperghetti** [comment]
@sergiodxa happening on 6.1.0, both localhost and AWS deploy
Output AWS: <img width="870" alt="Screenshot 2023-04-11 at 9 07 00 PM" src="https://user-images.githubusercontent.com/2907730/231347159-53833436-0827-40a6-997c-cd8f56295978.png">
Output Localhost: <img width="237" alt="Screenshot 2023-04-11 at 9 09 53 PM" src="https://user-images.githubusercontent.com/2907730/231347219-9d73d52e-8992-45ca-9e03-240d6e025735.png">

Code:
<img width="456" alt="Screenshot 2023-04-11 at 9 10 28 PM" src="https://user-images.githubusercontent.com/2907730/231347281-969e3b5e-b20d-4e1f-93e8-386818448e23.png">

Not sure what to do, but we need IP address for Meta Conversion API

**Comment by sergiodxa** [comment]
@sperghetti if you get `null` it's possible `getClientIPAddress` couldn't figure out the IP address of the user, the way it works is using a header (the list is on the README), in localhost it never works because you don't receive any of the headers, in production it will work if your deployment platform adds such header to the request Remix receives.

So what's most likely happening is that when you deploy your app you're not getting any of the supported headers, check the list of headers you receive and see if any of them includes the IP address, if it does so I will be happy to accept a PR to include support for that header.
