### ISSUE TITLE
Remix not found error when using pnpm

### ISSUE THREAD

**Issue by cevr** [sergiodxa/remix-utils#11]
Minimal reproduction

`npx create-remix@latest`

Use App server template -> typescript -> no npm install

`cd [created-folder]`

`pnpm i remix-utils`

Command fails with error in remix-utils postintall `cannot find remix`

**Comment by sergiodxa** [comment]
@cevr I think this should not be an issue anymore, Remix Utils latest version doesn't use remix and instead use the `@remix-run/*` packages.

If you keep having the issue, I think it may be because they are marked as peer dependencies and `pnpm` is not working with that for some reason, sadly I don't have any experience with `pnpm`
