### ISSUE TITLE
`namedAction` expects type of FormData instead of request

### ISSUE THREAD

**Issue by brandonpittman** [sergiodxa/remix-utils#124]
### Describe the bug

Passing a `Request` object to `namedAction` results in a TypeScript error. Seems to want a `FormData` object.

### Your Example Website or App

https://stackblitz.com/edit/node-imtmir?file=app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Create action with named action
2. Try to pass it `request` as shown in the remix-utils example

### Expected behavior

If should accept a `Request` object.

### Screenshots or Videos

<img width="854" alt="CleanShot 2022-12-10 at 20 33 45@2x" src="https://user-images.githubusercontent.com/967145/206852980-76d75599-5272-40ec-9dfc-75161db1e669.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 108

### Additional context

Looks similar to this. 

https://stackoverflow.com/questions/57314805/in-typescript-why-function-overloading-order-matters-only-when-the-overloaded-f

**Comment by jansedlon** [comment]
Actually the reason for this is that you don't return an instance of `Response` object.

**Comment by brandonpittman** [comment]
> Actually the reason for this is that you don't return an instance of `Response` object.

@jansedlon That makes sense, but it wasn't obvious. Thanks.

**Comment by jansedlon** [comment]
@brandonpittman No problem 😊 However I wouldn't mark this as closed since it breaks the whole end-to-end safety that Remix added with `LoaderArgs` and `ActionArgs`. We should bring this to attention of @sergiodxa .

I played a bit with the types and this is what I came up with to have fully typed response even with `namedAction`

Instead of this (current code)
```ts
declare type Actions = Record<string, () => Promise<Response>>;

export declare function namedAction(request: Request, actions: Actions): Promise<Response>;
```

We could change it to something like this

```ts
declare type ActionsWithTypedResponse = Record<string, () => Promise<TypedResponse>>;

declare type TypedActions<T extends ActionsWithTypedResponse> = {
  [K in keyof T]: T[K] extends () => Promise<TypedResponse<infer V>> ? TypedResponse<V> : never;
}

export declare function namedAction<T extends ActionsWithTypedResponse>(request: Request, actions: T): Promise<TypedActions<T>[keyof T]>;
```

It works quite well for me. I tried to use it with two named actions using `domain-functions` and `zod` and this is the return type of `namedAction`.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/13948180/208374439-c69ecf4a-36b6-4597-a613-b6ac52ffc1dd.png">

**Comment by sergiodxa** [comment]
To use TypedResponse I would have to do a major update since the current base version of Remix that Remix Utils support doesn't include it

I would work on an update for that and release a v6
